// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web_phong_kham_tu_nhan.Data;

#nullable disable

namespace web_phong_kham_tu_nhan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407111454_AddHoSoBacSi_AND_YeuCau")]
    partial class AddHoSoBacSi_AND_YeuCau
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.BacSi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuyenKhoaId")
                        .HasColumnType("int");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("diaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("tieuSu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenKhoaId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.BenhNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChuyenKhoaId")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LichSuYTe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenKhoaId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.ChuyenKhoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.HoSoBacSi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CapNhatLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChuyenMonSau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiThuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocHam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KinhNghiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamKinhNghiem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapCCHN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHanCCHN")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgonNgu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhamViHanhNghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCHN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruongDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId")
                        .IsUnique();

                    b.ToTable("HoSoBacSis");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.LichHen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int");

                    b.Property<int>("ChuyenKhoaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LyDoKham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("ChuyenKhoaId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.LichLamViecBacSi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<string>("CaLam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuGoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoXinNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoBenhNhanToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TaoLichBoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.ToTable("LichLamViecBacSis");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.YeuCauCapNhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacSiId")
                        .HasColumnType("int");

                    b.Property<string>("DuyetBoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuyetLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GiaTriCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaTriMoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoTuChoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TaoLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.ToTable("YeuCauCapNhats");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.BacSi", b =>
                {
                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("BacSis")
                        .HasForeignKey("ChuyenKhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenKhoa");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.BenhNhan", b =>
                {
                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("BenhNhans")
                        .HasForeignKey("ChuyenKhoaId");

                    b.Navigation("ChuyenKhoa");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.HoSoBacSi", b =>
                {
                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.BacSi", "BacSi")
                        .WithOne("HoSoBacSi")
                        .HasForeignKey("web_phong_kham_tu_nhan.Models.Entities.HoSoBacSi", "BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.LichHen", b =>
                {
                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.BacSi", "BacSi")
                        .WithMany("LichHens")
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.BenhNhan", "BenhNhan")
                        .WithMany("LichHens")
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.ChuyenKhoa", "ChuyenKhoa")
                        .WithMany("Appointments")
                        .HasForeignKey("ChuyenKhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");

                    b.Navigation("ChuyenKhoa");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.LichLamViecBacSi", b =>
                {
                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.BacSi", "BacSi")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.YeuCauCapNhat", b =>
                {
                    b.HasOne("web_phong_kham_tu_nhan.Models.Entities.BacSi", "BacSi")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.BacSi", b =>
                {
                    b.Navigation("HoSoBacSi");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.BenhNhan", b =>
                {
                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("web_phong_kham_tu_nhan.Models.Entities.ChuyenKhoa", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BacSis");

                    b.Navigation("BenhNhans");
                });
#pragma warning restore 612, 618
        }
    }
}
